spring:
  datasource:
    url: jdbc:postgresql://morapack-test-db.cfsefdaj5iud.us-east-1.rds.amazonaws.com:5434/morapackdb
    username: morapack
    password: UQ4jdLJKWULADFrryA4v
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: MoraPack
server:
  port: 8080
